filter:
  paths:
    - src/*
before_commands:
  - 'composer install --optimize-autoloader'
checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    php:
      version: 7.4
  tests:
    override:
      -
        command: 'composer test'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
tools:
  external_code_coverage: false
  php_mess_detector: true
  php_code_sniffer:
    config:
      standard: PSR12
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs:
      - tests
      - vendor
  php_cpd:
    enabled: true
    excluded_dirs:
      - tests
      - vendor
